# .github/workflows/cffconvert.yml - Enhanced CFF Conversion Workflow for Machineflow
# ===========================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===========================================================================
# Description: Powerful GitHub Actions workflow to validate, convert, and 
#              maintain Machineflow's CITATION.cff on ARM64 and x86 runners, 
#              with auto-PR updates and strict validation.
# Created: March 13, 2025
# Library: Machineflow (github.com/yourusername/machineflow)
# Version: 1.0.0
# Documentation: https://github.com/Zeppelin-Corporation/machineflow#readme
# ===========================================================================

name: CFF Conversion and Validation

on:
  push:
    branches:
      - main
    paths:
      - 'CITATION.cff'
      - '.github/workflows/cffconvert.yml'
  pull_request:
    paths:
      - 'CITATION.cff'
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Mondays at midnight UTC

jobs:
  validate-and-convert:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest-arm64]  # Multi-arch: x86_64 and ARM64
      fail-fast: false  # Continue even if one runner fails
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for version checks

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'  # If applicable

      # Install dependencies
      - name: Install cffconvert and tools
        run: |
          pip install cffconvert yamllint
          cffconvert --version

      # Lint CITATION.cff (extra validation)
      - name: Lint CITATION.cff
        run: |
          echo "Linting CITATION.cff for YAML compliance"
          yamllint -d "{extends: relaxed, rules: {line-length: disable}}" CITATION.cff

      # Validate CITATION.cff
      - name: Validate CITATION.cff
        run: |
          echo "Validating CITATION.cff on ${{ matrix.os }}"
          cffconvert --validate --verbose
        continue-on-error: false

      # Convert to BibTeX
      - name: Convert to BibTeX
        run: |
          echo "Converting to BibTeX"
          cffconvert --format bibtex --output CITATION.bib
          cat CITATION.bib

      # Convert to RIS
      - name: Convert to RIS
        run: |
          echo "Converting to RIS"
          cffconvert --format ris --output CITATION.ris
          cat CITATION.ris

      # Check version consistency
      - name: Verify version consistency
        run: |
          echo "Checking version consistency with repository"
          CFF_VERSION=$(grep '^version:' CITATION.cff | awk '{print $2}')
          REPO_VERSION="1.0.0"  # Replace with dynamic check if possible
          if [ "$CFF_VERSION" != "$REPO_VERSION" ]; then
            echo "Error: CITATION.cff version ($CFF_VERSION) does not match repo version ($REPO_VERSION)"
            exit 1
          fi

      # Upload artifacts
      - name: Upload citation files
        uses: actions/upload-artifact@v4
        with:
          name: citation-files-${{ matrix.os }}
          path: |
            CITATION.bib
            CITATION.ris
          retention-days: 60

      # Auto-update PR with converted files
      - name: Create or update PR with citation files
        if: github.event_name != 'pull_request' && matrix.os == 'ubuntu-latest'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-citation-files-${{ github.sha }}
          git add CITATION.bib CITATION.ris
          git commit -m "Update citation files from CITATION.cff" || echo "No changes to commit"
          git push origin update-citation-files-${{ github.sha }} --force
          gh pr create --title "Update citation files" \
                       --body "Auto-generated PR to update CITATION.bib and CITATION.ris" \
                       --base main \
                       --assignee "tilakrayal,Venkat6871" \
                       --reviewer "joker-eph,sanjoy" \
                       --label "citation,automation" || echo "PR already exists"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: validate-and-convert
    if: failure()
    steps:
      - name: Notify failure
        run: |
          echo "CFF validation or conversion failed. Assigned to: tilakrayal, Venkat6871"
          echo "Security contact: mihaimaruseac"
          gh issue comment ${{ github.event.number || github.sha }} \
            --body "CFF workflow failed. Please check logs. Assigned to @tilakrayal, @Venkat6871. Security: @mihaimaruseac"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}