# .github/workflows/cffconvert.yml
name: CFF Conversion and Validation

on:
  push:
    branches:
      - main
    paths:
      - 'CITATION.cff'
  pull_request:
    paths:
      - 'CITATION.cff'

jobs:
  validate-and-convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          pip install cffconvert
          cffconvert --version

      - name: Validate CITATION.cff
        run: |
          cffconvert --validate

      - name: Convert to BibTeX
        run: |
          cffconvert --format bibtex --output CITATION.bib

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: citation-files
          path: CITATION.bib
