name: Stale Issues and PRs
on:
  schedule:
    - cron: "0 0 * * *" # Daily
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue is stale (30 days inactive). Comment to keep it open."
          stale-pr-message: "This PR is stale (60 days inactive). Update or it will close."
          days-before-issue-stale: 30
          days-before-pr-stale: 60
          days-before-close: 7
          exempt-issue-labels: "critical,bug"
          exempt-pr-labels: "release"
