name: Machineflow Stale Issues and PRs Manager
on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch: # Allows manual triggering
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue has been inactive for 30 days and is now stale. Comment within 7 days to keep it open, or it will be closed."
          stale-pr-message: "This PR has been inactive for 60 days and is now stale. Update within 7 days, or it will be closed."
          close-issue-message: "This issue was closed due to 37 days of inactivity."
          close-pr-message: "This PR was closed due to 67 days of inactivity."
          days-before-issue-stale: 30
          days-before-pr-stale: 60
          days-before-close: 7
          exempt-issue-labels: "critical,bug,enhancement"
          exempt-pr-labels: "release,in-progress"
          operations-per-run: 100 # Limits API usage
      - name: Notify Slack on Closures
        if: steps.stale.outputs.closed-issues-prs > 0
        uses: slackapi/slack-github-action@v1.26.0
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "github-notifications"
          text: "Machineflow repo: ${{ steps.stale.outputs.closed-issues-prs }} stale issues/PRs closed today."
