name: Update Nightly
on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC
  workflow_dispatch: # Manual trigger
env:
  PYTHON_VERSION: "3.9"
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build Package
        run: |
          python -m build
      - name: Verify Package Metadata
        run: |
          twine check dist/*
      - name: Publish to TestPyPI
        run: |
          NIGHTLY_VERSION=$(date +%Y%m%d).nightly
          twine upload dist/* --repository-url https://test.pypi.org/legacy/ -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }} --verbose
      - name: Test Installation and Import
        run: |
          pip install --index-url https://test.pypi.org/simple/ --no-deps machineflow==${NIGHTLY_VERSION}
          python -c "import machineflow; print(f'Machineflow version: {machineflow.__version__}')"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-build
          path: dist/*
